export const adminSidebarMenu = [
  {
    type: "section",
    label: "OVERVIEW",
    items: [
      {
        type: "link",
        label: "Dashboard",
        path: "/admin/store",
        icon: "LayoutDashboard",
      },
      {
        type: "expandable",
        label: "Orders",
        icon: "FileText",
        subItems: [
          { label: "All", path: "/admin/store/orders/all" },
          { label: "Scheduled", path: "/admin/store/orders/scheduled" },
          { label: "Pending", path: "/admin/store/orders/pending" },
          { label: "Processing", path: "/admin/store/orders/processing" },
          { label: "Out For Delivery", path: "/admin/store/orders/food-on-the-way" },
          { label: "Delivered", path: "/admin/store/orders/delivered" },
          { label: "Cancelled", path: "/admin/store/orders/canceled" },
          { label: "Seller cancelled", path: "/admin/store/orders/restaurant-cancelled" },
          { label: "Payment Failed", path: "/admin/store/orders/payment-failed" },
          { label: "Refunded", path: "/admin/store/orders/refunded" },
          { label: "Offline Payments", path: "/admin/store/orders/offline-payments" },
          { label: "Abandoned", path: "/admin/store/orders/abandoned" },
          { label: "User Carts", path: "/admin/store/orders/user-carts" },
        ],
      },
      {
        type: "link",
        label: "Order Detect Delivery",
        path: "/admin/store/order-detect-delivery",
        icon: "Truck",
      },
    ],
  },
  {
    type: "section",
    label: "MANAGEMENT",
    items: [
      {
        type: "link",
        label: "Point of Sale",
        path: "/admin/store/point-of-sale",
        icon: "CreditCard",
      },
      {
        type: "link",
        label: "Product Approval",
        path: "/admin/store/food-approval",
        icon: "CheckCircle2",
      },
      {
        type: "expandable",
        label: "Products",
        icon: "Utensils",
        subItems: [
          { label: "Seller Products List", path: "/admin/store/products" },
          { label: "Seller Add-ons List", path: "/admin/store/addons" },
        ],
      },
      {
        type: "link",
        label: "Categories",
        icon: "FolderTree",
        path: "/admin/store/categories",
      },
      {
        type: "link",
        label: "Zone Setup",
        path: "/admin/store/zone-setup",
        icon: "MapPin",
      },
      {
        type: "expandable",
        label: "Sellers",
        icon: "UtensilsCrossed",
        subItems: [
          { label: "Sellers List", path: "/admin/store/sellers" },
          { label: "New Seller Requests", path: "/admin/store/sellers/joining-request" },
          { label: "Unregistered Sellers", path: "/admin/store/sellers/unregistered" },
          { label: "Seller Reviews", path: "/admin/store/sellers/reviews" },
          { label: "Seller Complaints", path: "/admin/store/sellers/complaints" },
          { label: "Seller Settings", path: "/admin/store/sellers/settings" },
          { label: "Subscription Settings", path: "/admin/store/sellers/subscription-settings" },
          { label: "Subscription Billing", path: "/admin/store/sellers/subscription-history" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "DELIVERY",
    items: [
      { type: "link", label: "Delivery & Platform Fee", path: "/admin/store/fee-settings", icon: "DollarSign" },
      { type: "link", label: "Delivery Withdrawal", path: "/admin/store/delivery-withdrawal", icon: "Wallet" },
      { type: "link", label: "Delivery boy Wallet", path: "/admin/store/delivery-boy-wallet", icon: "PiggyBank" },
      { type: "link", label: "Delivery Emergency Help", path: "/admin/store/delivery-emergency-help", icon: "Phone" },
      { type: "link", label: "Delivery Support Tickets", path: "/admin/store/delivery-support-tickets", icon: "MessageSquare" },
      { type: "link", label: "Order Reassignment Requests", path: "/admin/store/delivery-order-reassignment-requests", icon: "AlertTriangle" },
      {
        type: "expandable",
        label: "Deliveryman",
        icon: "Package",
        subItems: [
          { label: "New Join Request", path: "/admin/store/delivery-partners/join-request" },
          { label: "Deliveryman List", path: "/admin/store/delivery-partners" },
          { label: "Live Tracking", path: "/admin/store/delivery-partners/live-tracking" },
          { label: "Deliveryman Reviews", path: "/admin/store/delivery-partners/reviews" },
          { label: "Bonus", path: "/admin/store/delivery-partners/bonus" },
          { label: "Earning Addon", path: "/admin/store/delivery-partners/earning-addon" },
          { label: "Earning Addon History", path: "/admin/store/delivery-partners/earning-addon-history" },
          { label: "Delivery Earning", path: "/admin/store/delivery-partners/earnings" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "CUSTOMERS & SUPPORT",
    items: [
      {
        type: "link",
        label: "Customers",
        path: "/admin/store/customers",
        icon: "Users",
      },
      {
        type: "link",
        label: "Support Tickets (User & Seller)",
        path: "/admin/store/support-tickets",
        icon: "MessageSquare",
      },
      { type: "link", label: "User Feedback", path: "/admin/store/contact-messages", icon: "Mail" },
      { type: "link", label: "Safety Emergency Reports", path: "/admin/store/safety-emergency-reports", icon: "AlertTriangle" },
    ],
  },
  {
    type: "section",
    label: "MARKETING",
    items: [
      {
        type: "link",
        label: "Seller Coupons & Offers",
        path: "/admin/store/coupons",
        icon: "Gift",
      },
      { type: "link", label: "Referral Settings", path: "/admin/store/referral-settings", icon: "Gift" },
      { type: "link", label: "Landing Page Management", path: "/admin/store/hero-banner-management", icon: "Image" },
      { type: "link", label: "Promotional Banners", path: "/admin/store/promotional-banner", icon: "Megaphone" },
    ],
  },
  {
    type: "section",
    label: "FINANCE & REPORTS",
    items: [
      { type: "link", label: "Wallet Dashboard", path: "/admin/store/wallet-dashboard", icon: "Wallet" },
      { type: "link", label: "Transaction Report", path: "/admin/store/transaction-report", icon: "FileText" },
      { type: "link", label: "Order Report", path: "/admin/store/order-report/regular", icon: "FileText" },
      { type: "link", label: "Tax Report", path: "/admin/store/tax-report", icon: "Receipt" },
      { type: "link", label: "Restaurant Withdraws", path: "/admin/store/restaurant-withdraws", icon: "CreditCard" },
      {
        type: "expandable",
        label: "Restaurant Report",
        icon: "FileText",
        subItems: [{ label: "Restaurant Report", path: "/admin/store/restaurant-report" }],
      },
      {
        type: "expandable",
        label: "Customer Report",
        icon: "FileText",
        subItems: [{ label: "Feedback Experience", path: "/admin/store/customer-report/feedback-experience" }],
      },
    ],
  },
  {
    type: "section",
    label: "CONFIGURATION",
    items: [
      {
        type: "expandable",
        label: "Appearance",
        icon: "Palette",
        subItems: [
          { label: "Business Setup", path: "/admin/store/business-setup" },
          { label: "About Us", path: "/admin/store/pages-social-media/about" },
          { label: "Terms & Conditions", path: "/admin/store/pages-social-media/terms" },
          { label: "Privacy Policy", path: "/admin/store/pages-social-media/privacy" },
          { label: "Support", path: "/admin/store/pages-social-media/support" },
          { label: "Refund Policy", path: "/admin/store/pages-social-media/refund" },
          { label: "Shipping Policy", path: "/admin/store/pages-social-media/shipping" },
          { label: "Cancellation Policy", path: "/admin/store/pages-social-media/cancellation" },
        ],
      },
      {
        type: "expandable",
        label: "Settings",
        icon: "Settings",
        subItems: [
          { label: "Broadcast Notification", path: "/admin/store/broadcast-notification" },
          { label: "Survey", path: "/admin/store/survey" },
          { label: "Feature Settings", path: "/admin/store/feature-settings" },
          { label: "Power Scanning", path: "/admin/store/power-scanning" },
          { label: "Sub Admin List", path: "/admin/store/employees" },
        ],
      },
    ],
  },
];
